### ISSUE TITLE
Support wildcard ignores

### ISSUE THREAD

**Issue by kostyay** [stormcat24/protodep#46]
Hey
Thanks for the great tool, its super handy.
It will be great if it would be possible to specify glob wildcards (eg `*.go` or `*/**/*.go`) for the ignores directive
Currently you have to either provide a full path or the prefix which also has to be full.

**Comment by stormcat24** [comment]
@kostyay Good suggestion. 
I plan to implement this, buf if you're in a hurry, you can send me a PR.

**Comment by kostyay** [comment]
I will see what I can do :)

**Comment by kostyay** [comment]
https://github.com/stormcat24/protodep/pull/47

**Comment by stormcat24** [comment]
@kostyay This feature is released as 0.0.9 🙏 
https://github.com/stormcat24/protodep/releases/tag/0.0.9
