### ISSUE TITLE
How to fetch repository with https basic auth

### ISSUE THREAD

**Issue by Warashi** [stormcat24/protodep#52]
Hi

I want to fetch repository with https and basic auth.
How to do this?

**Comment by stormcat24** [comment]
@Warashi  Not now.
I have time this weekend, so I'll support this issue!

**Comment by stormcat24** [comment]
@Warashi 
I released this features in version [0.1.0](https://github.com/stormcat24/protodep/releases/tag/0.1.0)
Please check the [README](https://github.com/stormcat24/protodep#getting-via-https) for how to use it.

**Comment by Warashi** [comment]
Thank you so much. I'll try.

**Comment by Warashi** [comment]
I tried `--use-https`, `--basic-auth-username` and `--basic-auth-password` but protodep cmd tried to connect with ssh protocol 🤔 
```
[INFO] force update = true
[INFO] cleanup cache = false
[INFO] identity file =
[INFO] use https = true
[INFO] https basic auth username = x-access-token
[INFO] https basic auth username = xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
Error: fetch repository is failed: ssh: handshake failed: ssh: unable to authenticate, attempted methods [none publickey], no supported methods remain
```

**Comment by stormcat24** [comment]
🤔 
@Warashi How did you write protodep.toml?

**Comment by Warashi** [comment]
Sorry, the cause was my `~/.protodep`, I fetched same repository with ssh before.
I deleted `~/.protodep`, then I succeeded to fetch with https and basic auth.

**Comment by stormcat24** [comment]
Oh, that was good!

If the previous cache remains, it will be confusing.
I would like to improve this in the future 🙏

**Comment by stormcat24** [comment]
Thank you for your feature request. I close is this close.

`use-https` option may be deprecated in the near future. #57
