### ISSUE TITLE
Specify transport protocol in protodep.toml

### ISSUE THREAD

**Issue by stormcat24** [stormcat24/protodep#57]
#51 
- `git+ssh`
- `https://`
- If neither is set.

**Comment by stormcat24** [comment]
If this specification is added, `use-https` option will probably not be needed.

**Comment by Warashi** [comment]
In my team, protodep.toml is in repository and every user choose protocol by option.
So specifying transport protocol in protodep.toml may be not used.
`use-https` is useful in my case, so deprecation is unhappy.

**Comment by stormcat24** [comment]
I see. I find it useful in that use case.
If no protocol is specified in protodep.toml, it may be better to give priority to `use-https` options.

Thank you for your good opinion!
