### ISSUE TITLE
Feature: Whitelist option

### ISSUE THREAD

**Issue by n0v1** [stormcat24/protodep#75]
If you only need a few protos from a repository that has lots of proto files in it, specifying an ignores array to exclude everything that is NOT needed is cumbersome. It would be more convenient to have a "whitelist" of files/paths that should be downloaded and ignore everything else.

Not sure if "whitelist" would be the best name for this option. Maybe "match" or "include" would be a better fit. Other ideas?

**Comment by stormcat24** [comment]
@n0v1 This is nice idea. I agree with your opinion.
I think "include" is better.

**Comment by n0v1** [comment]
Thank you both for adding this feature! Will test it during the next couple of days.

**Comment by n0v1** [comment]
Works great!
